version: '3.8'

services:

  clientcredentialserver:
    container_name: clientcredentialserver
    build:
      context: .
      dockerfile: client_credential_server.dockerfile
    ports:
      - "8080:8080"
      - "8090:8090"
    network_mode: host






