server:
  port: 8083

spring:
  application:
    name: "ResourceServer_AGSR_TestTask"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8082
          jwk-set-uri: http://127.0.0.1:8082/oauth2/jwks

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        hibernate.default_schema: res_sch
        globally_quoted_identifiers: true
        show_sql: true
        format_sql: true
        jdbc:
          lob:
            non-contextual-creation: true
  liquibase:
    change-log: classpath:/db/changelog/app-changelog.yml
    default-schema: res_sch
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: sA#259979148307

preliquibase:
  sqlScriptReferences: classpath:/db/preliquibase/create_schema.sql

logging:
  level:
    org:
      springframework:
        security: trace
        transaction:
          interceptor: trace
    root: INFO
  file:
    path: src/main/resources/logs
    name: src/main/resources/logs/resource-service.log

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  show-actuator: true
  swagger-ui:
    oauth:
      client-id: client
      client-secret: secret
    oauth2-redirect-url: http://127.0.0.1:8083/api/v1/patients

info:
  application:
    name: ${spring.application.name}
    description: Resource server in AGSR test task
