server:
  port: 8082

spring:
  application:
    name: "AuthorizationServer_AGSR_TestTask"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hibernate.default_schema: auth_sch
        globally_quoted_identifiers: true
        show_sql: true
        format_sql: true
        jdbc:
          lob:
            non-contextual-creation: true
  liquibase:
    change-log: classpath:/db/changelog/app-changelog.yml
    default-schema: auth_sch
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: sA#259979148307

preliquibase:
  sqlScriptReferences: classpath:/db/preliquibase/create_schema.sql

logging:
  level:
    org:
      springframework:
        security: trace
    root: INFO
  file:
    path: src/main/resources/logs
    name: src/main/resources/logs/authorization-service.log
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
springdoc:
  show-actuator: true
  swagger-ui:
    oauth:
      client-id: client
      client-secret: secret
    oauth2-redirect-url: http://127.0.0.1:8080/swagger-ui/oauth2-redirect.html

info:
  application:
    name: ${spring.application.name}
    description: Authorization server in AGSR test task